version: '3'

services:
  mongo:
    image: mongo:8.0.0-rc9
    container_name: mongo_nautilus
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME:
      MONGO_INITDB_ROOT_PASSWORD:
    volumes:
      - ./mongo:/data/db
    ports:
      - "27017:27017"
    command: --auth
